### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by nol166** [mmotti/pihole-regex#23]
**Issue**: After running `curl -sSl https://raw.githubusercontent.com/mmotti/pihole-regex/master/install.py | sudo python3` I got an error:

```
  File "<stdin>", line 65
    print(f'{path_pihole} was not found')
                                       ^
SyntaxError: invalid syntax
```

**Pihole Version:**
Pi-hole version is v4.3.2 (Latest: v4.3.2)
AdminLTE version is v4.3.3 (Latest: v4.3.3)
FTL version is v4.3.1 (Latest: v4.3.1)

**Comment by Suprcheese** [comment]
This looks to be the same issue as: https://github.com/mmotti/pihole-regex/issues/16

**Comment by mmotti** [comment]
Yes :-) this is due to the script requiring Python 3.6+

This fix would be to use the workaround in the link above.

I need to see if I can add a warning / stop within the script for this
issue. I hadn't realised how many people were using older operating systems

**Comment by nol166** [comment]
Ah, yeah I haven't updated the OS in a year or so. I ended up just running `sudo nano /etc/pihole/regex.list` to add the filters. Still cool that you guys have a script to add them though.

**Comment by mmotti** [comment]
Yeah, that will be why :-) the culprit is the f strings in python. They are
much more flexible but only supported in 3.6+

Glad you got it working though, either way. The script was made initially
because of the switch to a database in pihole v5+ - you'll notice from that
point, sadly, you won't have the ability to manipulate a text file and it's
currently a case of adding / deleting them one by one (at least in the gui).

**Comment by mmotti** [comment]
Have added a little note to the main readme here: https://github.com/mmotti/pihole-regex/commit/d34a744a812b315120e05d21e8ef022d0ee3405b
