### ISSUE TITLE
Is not really an issue, but you could add my list too

### ISSUE THREAD

**Issue by tutyamxx** [mmotti/pihole-regex#33]
https://github.com/tutyamxx/Pihole-BlacklistRegex-AutomaticAdd/blob/master/piregex.sh

:) Hope it helps you

**Comment by mmotti** [comment]
Hi,

The majority of these regexps look to be from my original list and a few of which I have since purposely removed due to large amounts of false positives.

I can see that you've added a few domain wildcards etc. which I am trying to avoid for now as it's my goal to have as few expressions as possible to cover a broad list of domains, as opposed to individual wildcards. Wildcards are also typically user preference.

I have to be very careful with how many regular expressions are added to this list as they are very expensive resource wise compared to standard domain lookups.

**Comment by tutyamxx** [comment]
Fair enough. 👍
