### ISSUE TITLE
Missing some FB non-US FQDN

### ISSUE THREAD

**Issue by mettacrawler** [mmotti/pihole-regex#35]
```
$ host facebook.co.uk 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases: 

facebook.co.uk has address 216.239.34.21
facebook.co.uk has address 216.239.32.21
facebook.co.uk has address 216.239.38.21
facebook.co.uk has address 216.239.36.21
```
Facebook has DNS for more countries than just the UK.

Probably:

`^(.+[_.-])?(facebook|fb(cdn|sbx)?|tfbnw)\.(co\.)?[^.]+$`

**Comment by mmotti** [comment]
Hi,

This is a variation of the regexp that I had considered before, however
after some testing I had deemed it unnecessary.

If I remember correctly, the .co.uk domain redirects to a Google 404 page,
and all other Facebook tlds (that I had thought to test) seemed to redirect
to the parent .com tld

If this has changed since I last looked, then by all means I will look at
this or a variation of :-)

>
>

**Comment by mmotti** [comment]
Closing for now for the FB example as it seems that all of the domains point back to the parent domain which is blocked regardless :)

Will re-visit in future potentially if this changes
