### ISSUE TITLE
How to use this with adguard?

### ISSUE THREAD

**Issue by whisperdancer** [mmotti/pihole-regex#65]
I was using pihole for a long time and have switched to adguard. My favorite feature of pihole was this script. Is there a way to adapt it for use with adguard?

Thank you!

**Comment by mmotti** [comment]
I haven't used Pihole or AdGuard for some time but I made a separate repo for that a little while ago.

If you're referring to AdGuard Home - Assuming they haven't changed the regex syntax since the last time I used it you should just be able to add the following as a Blocklist address:

https://raw.githubusercontent.com/mmotti/adguard-home-filters/master/regex.txt

**Comment by whisperdancer** [comment]
Thanks, I noticed your lines start with /^ and according to adguard home docs:
/REGEX/:block access to domains matching the specified regular expression.

Does this mean your list won't be interpreted as regex under adguard home? Would your list have to be update each line to something like this for example:
From /^(.+[_.-])?adse?rv(er?|ice)?s?[0-9]*[_.-]/ to /REGEX/^(.+[_.-])?adse?rv(er?|ice)?s?[0-9]*[_.-]/

**Comment by mmotti** [comment]
No - The list should be fine as is.

See here: https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#regular-expressions

The syntax they use for parsing regular expressions is basically:

`/regexphere/` - this blocks domains matching a regular expression
`@@/regexphere/` - this whitelists domains matching a regular expression 

They also include an `$important` flag but I've never delved into it in enough detail to see where it should be used.

**Comment by whisperdancer** [comment]
Perfect, thank you for the super quick response!

**Comment by whisperdancer** [comment]
For phole you had a cron that updates your list weekly. Is there a similar cron available for AGH? Thank you.

**Comment by mmotti** [comment]
It's 

> For phole you had a cron that updates your list weekly. Is there a similar cron available for AGH? Thank you.

It's not necessary for AGH as it supports fetching the list periodically out of the box (as with the other host files).

It was only necessary with Pihole due to the fact that you had to programmatically add the lines to the database as it didn't support fetching them from a host file.

It's part of the reason I migrated to AGH whilst I was still using DNS blockers - It became a far superior / better polished product in comparison to Pihole.

**Comment by whisperdancer** [comment]
Great, good to know. I agree, which is why I moved from pihole to AGH. Also, much easier to setup AGH with wireguard vpn IMHO. Thanks again for your great list and your support!

**Comment by mmotti** [comment]
Yep and a much cleaner install / uninstall. I hated the fact that Pihole left so many dependencies that it installed on the initial setup. It just left so much stuff behind whereas the AdGuard Home is a single executable. It was just miles better in a lot of respects. Though having said that I think they later released a docker image.

I moved away from them as I have very few devices and on those devices I'd just use Brave browser (phone) or Firefox with uBlock Origin on my PC. Other devices like my TV etc get tunneled through a VPN at the router and use an adblocked DNS address from my VPN provider.

With adblock within browsers on my phone or even with the AdGuard app on Android, or an adblocker on my PC's web browser I just had no real need for anything else. 

It would also annoy me that shopping links from Google and areas of Amazon wouldn't work because of the limited nature of DNS filtering.

Filter list blocking is significantly better than blanket DNS blocking. It just caught too many false positives in my experience and became a nuisance.

**Comment by whisperdancer** [comment]
Very interesting. Thanks for sharing your experience. I also switched to brave browser on my mobile devices as they offer commercial free youbute, basically getting youtube premium for free, but stick with firefox for my PC. I haven't had the issue with google or amazon, at least not yet.
